using NAudio.Wave;

namespace Mapping_Tools_Core.Audio.Samples {
    /// <summary>
    /// Sample generator that generates wave audio.
    /// </summary>
    public interface IAudioSampleGenerator : ISampleGenerator {
        /// <summary>
        /// Generates a new <see cref="ISampleProvider"/> with the sound of this generator.
        /// 
        /// <remarks>
        /// This <see cref="ISampleProvider"/> instance should be discarded before a new
        /// <see cref="ISampleProvider"/> is generated by this generator.
        /// </remarks>
        /// </summary>
        /// <returns></returns>
        ISampleProvider GetSampleProvider();
    }
}