name: Release

on:
  push:
    branches: [ master ]
    tags:
      - "v*.*.*"

jobs:
  publish:
    name: release version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
          
      - name: generate release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false

